services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  api:
    build:
      context: ./api
    container_name: etnair_api
    environment:
      DB_HOST: db
      DB_USER: etnair_user
      DB_PASSWORD: etnair_pass
      DB_NAME: etnair_db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - etnair_network

volumes:
  db_data:
  pgadmin-data:

networks:
  etnair_network:
    driver: bridge